<?php // this is an autogenerated file - do not edit (created Mon, 17 Oct 2011 19:36:58 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'suxxcommentcontroller' => '/controller/commentcontroller.php',
            'suxxcontroller' => '/classes/controller.php',
            'suxxdatabase' => '/classes/database.php',
            'suxxdatabaseresult' => '/classes/database.php',
            'suxxerrorcontroller' => '/controller/errorcontroller.php',
            'suxxerrorview' => '/views/errorview.php',
            'suxxfactory' => '/classes/factory.php',
            'suxxfrontcontroller' => '/classes/front.php',
            'suxxhomecontroller' => '/controller/homecontroller.php',
            'suxxlogincontroller' => '/controller/logincontroller.php',
            'suxxproductcontroller' => '/controller/productcontroller.php',
            'suxxregistercontroller' => '/controller/registercontroller.php',
            'suxxrequest' => '/classes/request.php',
            'suxxresponse' => '/classes/response.php',
            'suxxresponseexception' => '/classes/response.php',
            'suxxstaticview' => '/views/staticview.php',
            'suxxviewinterface' => '/classes/viewinterface.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
